apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-vault-secrets-sync
  namespace: default
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: vault-sync
          containers:
          - name: vault-sync
            image: david13356/vault-secrets-sync:latest
            env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_PREFIX_KEY_PATH
              value: "k8s/metadata/prod/apps/"
            - name: VAULT_TOKEN
              value: "hvs.CAESIM8nICe1DDAmwwjMJERQibHWDUgF-1CMLAKPL2l__jDXGh4KHGh2cy5nNWprZFlYV2lvcmJYWnhoZGVVSE9OSmg"
            - name: NAMESPACE
              value: "default"
          restartPolicy: OnFailure

