apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-vault-secrets-sync
  namespace: default
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: vault-sync
          containers:
          - name: vault-sync
            image: david13356/vault-secrets-sync:latest
            env:
            - name: VAULT_ADDR
              value: "http://vault:8200"
            - name: VAULT_PREFIX_KEY_PATH
              value: "k8s/metadata/prod/apps/"
            - name: SECRET_STORE_REF
              value: "vault-backend"
            - name: VAULT_TOKEN
              value: "TOKEN-HERE"
            - name: NAMESPACE
              value: "default"
          restartPolicy: OnFailure

